#pragma checksum "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/BasicComponent.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "3708c9fcd2e1ecb6cbaba92bcc60927f830690f42092c4aa1a7275c2f37020fd"
// <auto-generated/>
#pragma warning disable 1591
namespace __GeneratedComponent
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class AspNetCore_3708c9fcd2e1ecb6cbaba92bcc60927f830690f42092c4aa1a7275c2f37020fd : global::Microsoft.AspNetCore.Components.ComponentBase, IDisposable
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "class", 
#nullable restore
#line (2,14)-(2,29) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/BasicComponent.cshtml"
this.ToString()

#line default
#line hidden
#nullable disable
            );
            __builder.AddMarkupContent(2, "\r\n    Hello world\r\n    ");
            __builder.AddContent(3, 
#nullable restore
#line (4,6)-(4,35) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/BasicComponent.cshtml"
string.Format("{0}", "Hello")

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
        }
        #pragma warning restore 1998
#nullable restore
#line (7,13)-(9,1) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/BasicComponent.cshtml"

    void IDisposable.Dispose(){ }

#line default
#line hidden
#nullable disable

    }
}
#pragma warning restore 1591
