#pragma checksum "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/InjectWithKey.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "d201ecac63a18768701926f12ca75703f61ae21a3fac9eee4ae94b14be150e27"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCoreGeneratedDocument.TestFiles_IntegrationTests_CodeGenerationIntegrationTest_InjectWithKey), @"mvc.1.0.view", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/InjectWithKey.cshtml")]
namespace AspNetCoreGeneratedDocument
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Mvc;
    using global::Microsoft.AspNetCore.Mvc.Rendering;
    using global::Microsoft.AspNetCore.Mvc.ViewFeatures;
    #line default
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha256", @"d201ecac63a18768701926f12ca75703f61ae21a3fac9eee4ae94b14be150e27", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/InjectWithKey.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemMetadataAttribute("Identifier", "/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/InjectWithKey.cshtml")]
    [global::System.Runtime.CompilerServices.CreateNewOnMetadataUpdateAttribute]
    #nullable restore
    internal sealed class TestFiles_IntegrationTests_CodeGenerationIntegrationTest_InjectWithKey : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<
#nullable restore
#line (1,8)-(1,15) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/InjectWithKey.cshtml"
MyModel

#line default
#line hidden
#nullable disable
    >
    #nullable disable
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
        }
        #pragma warning restore 1998
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<MyModel> Html { get; private set; } = default!;
        #nullable disable
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute(Key = "SomeKey")]
        public 
#nullable restore
#line (5,14)-(5,23) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/InjectWithKey.cshtml"
MyService<MyModel>

#line default
#line hidden
#nullable disable
         
#nullable restore
#line (5,32)-(5,37) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/InjectWithKey.cshtml"
Html2

#line default
#line hidden
#nullable disable
         { get; private set; }
         = default!;
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute(Key = "SomeKey")]
        public 
#nullable restore
#line (4,14)-(4,19) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/InjectWithKey.cshtml"
MyApp

#line default
#line hidden
#nullable disable
         
#nullable restore
#line (4,20)-(4,35) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/InjectWithKey.cshtml"
MyPropertyName2

#line default
#line hidden
#nullable disable
         { get; private set; }
         = default!;
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute(Key = "KeyOne")]
        public 
#nullable restore
#line (2,14)-(2,19) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/InjectWithKey.cshtml"
MyApp

#line default
#line hidden
#nullable disable
         
#nullable restore
#line (2,20)-(2,34) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/InjectWithKey.cshtml"
MyPropertyName

#line default
#line hidden
#nullable disable
         { get; private set; }
         = default!;
    }
}
#pragma warning restore 1591
