#pragma checksum "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/MixKeyedInject.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "0c66f7428f024653c40cbe464ecbbc61c0469cca0652db4f6439f5889a52d9e1"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCoreGeneratedDocument.TestFiles_IntegrationTests_CodeGenerationIntegrationTest_MixKeyedInject), @"mvc.1.0.view", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/MixKeyedInject.cshtml")]
namespace AspNetCoreGeneratedDocument
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Mvc;
    using global::Microsoft.AspNetCore.Mvc.Rendering;
    using global::Microsoft.AspNetCore.Mvc.ViewFeatures;
    #line default
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha256", @"0c66f7428f024653c40cbe464ecbbc61c0469cca0652db4f6439f5889a52d9e1", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/MixKeyedInject.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemMetadataAttribute("Identifier", "/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/MixKeyedInject.cshtml")]
    [global::System.Runtime.CompilerServices.CreateNewOnMetadataUpdateAttribute]
    #nullable restore
    internal sealed class TestFiles_IntegrationTests_CodeGenerationIntegrationTest_MixKeyedInject : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<
#nullable restore
#line (1,8)-(1,15) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/MixKeyedInject.cshtml"
MyModel

#line default
#line hidden
#nullable disable
    >
    #nullable disable
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public 
#nullable restore
#line (8,9)-(8,14) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/MixKeyedInject.cshtml"
MyApp

#line default
#line hidden
#nullable disable
         
#nullable restore
#line (8,15)-(8,30) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/MixKeyedInject.cshtml"
MyPropertyName2

#line default
#line hidden
#nullable disable
         { get; private set; }
         = default!;
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public 
#nullable restore
#line (4,9)-(4,18) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/MixKeyedInject.cshtml"
MyService<MyModel>

#line default
#line hidden
#nullable disable
         
#nullable restore
#line (4,27)-(4,37) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/MixKeyedInject.cshtml"
ServiceOne

#line default
#line hidden
#nullable disable
         { get; private set; }
         = default!;
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public 
#nullable restore
#line (3,9)-(3,14) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/MixKeyedInject.cshtml"
MyApp

#line default
#line hidden
#nullable disable
         
#nullable restore
#line (3,15)-(3,29) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/MixKeyedInject.cshtml"
MyPropertyName

#line default
#line hidden
#nullable disable
         { get; private set; }
         = default!;
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<MyModel> Html { get; private set; } = default!;
        #nullable disable
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute(Key = "KeyThree")]
        public 
#nullable restore
#line (9,14)-(9,19) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/MixKeyedInject.cshtml"
MyApp

#line default
#line hidden
#nullable disable
         
#nullable restore
#line (9,20)-(9,35) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/MixKeyedInject.cshtml"
MyPropertyName3

#line default
#line hidden
#nullable disable
         { get; private set; }
         = default!;
    }
}
#pragma warning restore 1591
