// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line hidden
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "input");
            __builder.AddAttribute(1, "@rendermode", "Microsoft.AspNetCore.Components.Web.RenderMode.Server");
            __builder.CloseElement();
            __builder.AddMarkupContent(2, "\r\n");
            __builder.OpenElement(3, "input");
            __builder.AddAttribute(4, "@rendermode", 
#nullable restore
#line 2 "x:\dir\subdir\Test\TestComponent.cshtml"
                      str

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(5, "\r\n");
            __builder.OpenElement(6, "input");
            __builder.AddAttribute(7, "@rendermode", 
#nullable restore
#line 3 "x:\dir\subdir\Test\TestComponent.cshtml"
                      Microsoft.AspNetCore.Components.Web.RenderMode.Server

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
        }
        #pragma warning restore 1998
#nullable restore
#line 6 "x:\dir\subdir\Test\TestComponent.cshtml"
 
    string str = "abc";

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
