// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
    public class TestComponent : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder builder)
        {
<<<<<<< HEAD
            builder.AddContent(0, "<!DOCTYPE html>\r\n");
=======
            base.BuildRenderTree(builder);
            builder.AddMarkupContent(0, "<!DOCTYPE html>\r\n");
>>>>>>> Prevent newlines from being encoded in the output
            builder.AddMarkupContent(1, "<div>\r\n</div>");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
