// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (1,2)-(2,1) "x:\dir\subdir\Test\_Imports.razor"
using System.Text

#nullable disable
    ;
#nullable restore
#line (2,2)-(3,1) "x:\dir\subdir\Test\_Imports.razor"
using System.Reflection

#line default
#line hidden
#nullable disable
    ;
    [global::Microsoft.AspNetCore.Components.LayoutAttribute(typeof(MainLayout))]
    #nullable restore
    public partial class _Imports : System.Object
    #nullable disable
    {
        #pragma warning disable 1998
        protected void Execute()
        {
            __builder.AddContent(0, 
#nullable restore
#line (5,2)-(5,5) "x:\dir\subdir\Test\_Imports.razor"
Foo

#line default
#line hidden
#nullable disable
            );
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
