blank_issues_enabled: true
contact_links:
  - name: Issue with Razor compiler
    url:  https://github.com/dotnet/razor-compiler/issues/new/choose
    about: Please open issues relating to the Razor compiler in dotnet/razor-compiler.
