// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,39) "x:\dir\subdir\Test\TestComponent.cshtml"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<global::
#nullable restore
#line (3,2)-(3,10) "x:\dir\subdir\Test\TestComponent.cshtml"
Test.Col

#line default
#line hidden
#nullable disable
            >(0);
            __builder.AddAttribute(1, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.AddContent(2, "in markup");
            }
            ));
            __builder.CloseComponent();
#nullable restore
#line (4,3)-(5,1) "x:\dir\subdir\Test\TestComponent.cshtml"


#line default
#line hidden
#nullable disable

            __builder.OpenComponent<global::
#nullable restore
#line (5,6)-(5,14) "x:\dir\subdir\Test\TestComponent.cshtml"
Test.Col

#line default
#line hidden
#nullable disable
            >(3);
            __builder.AddAttribute(4, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.AddContent(5, "in code block");
            }
            ));
            __builder.CloseComponent();
#nullable restore
#line (6,1)-(6,31) "x:\dir\subdir\Test\TestComponent.cshtml"
    RenderFragment template = 

#line default
#line hidden
#nullable disable

            (__builder2) => {
                __builder2.OpenComponent<global::
#nullable restore
#line (6,33)-(6,41) "x:\dir\subdir\Test\TestComponent.cshtml"
Test.Col

#line default
#line hidden
#nullable disable
                >(6);
                __builder2.AddAttribute(7, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    __builder3.AddContent(8, "in template");
                }
                ));
                __builder2.CloseComponent();
            }
#nullable restore
#line (6,64)-(7,1) "x:\dir\subdir\Test\TestComponent.cshtml"
;

#line default
#line hidden
#nullable disable

        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
