#pragma checksum "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/AttributeDirective.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "182a864a99c94c5a3bbb535723dfb08ad1a97865628ed562e8f2c949e7098074"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles.TestFiles_IntegrationTests_CodeGenerationIntegrationTest_AttributeDirective_Runtime), @"default", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/AttributeDirective.cshtml")]
namespace Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles
{
    #line hidden
#nullable restore
#line (1,12)-(1,68) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/AttributeDirective.cshtml"
[System.Runtime.InteropServices.DllImport("user32.dll")]

#line default
#line hidden
#nullable disable

#nullable restore
#line (2,12)-(2,63) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/AttributeDirective.cshtml"
[assembly: AssemblyTitleAttribute("Some assembly")]

#line default
#line hidden
#nullable disable

#nullable restore
#line (3,12)-(3,78) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/AttributeDirective.cshtml"
[DllImport("user32.dll", SetLastError=false, ExactSpelling=false)]

#line default
#line hidden
#nullable disable

#nullable restore
#line (4,12)-(4,56) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/AttributeDirective.cshtml"
[Conditional("DEBUG"), Conditional("TEST1")]

#line default
#line hidden
#nullable disable

    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha256", @"182a864a99c94c5a3bbb535723dfb08ad1a97865628ed562e8f2c949e7098074", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/AttributeDirective.cshtml")]
    public class TestFiles_IntegrationTests_CodeGenerationIntegrationTest_AttributeDirective_Runtime
    {
        #pragma warning disable 1998
        public async System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\nHello World");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
