#pragma checksum "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/DesignTime.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "81bc9372da7d25ed6342dfd5b1067004013e6b4791921ce725e71f4c9eb90f85"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles.TestFiles_IntegrationTests_CodeGenerationIntegrationTest_DesignTime_Runtime), @"default", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/DesignTime.cshtml")]
namespace Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha256", @"81bc9372da7d25ed6342dfd5b1067004013e6b4791921ce725e71f4c9eb90f85", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/DesignTime.cshtml")]
    public class TestFiles_IntegrationTests_CodeGenerationIntegrationTest_DesignTime_Runtime
    {
        #pragma warning disable 1998
        public async System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("<div>\r\n");
#nullable restore
#line (2,14)-(3,1) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/DesignTime.cshtml"
for(int i = 1; i <= 10; i++) {

#line default
#line hidden
#nullable disable

            WriteLiteral("    <p>This is item #");
            Write(
#nullable restore
#line (3,23)-(3,24) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/DesignTime.cshtml"
i

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("</p>\r\n");
#nullable restore
#line (4,1)-(5,1) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/DesignTime.cshtml"
            }

#line default
#line hidden
#nullable disable

            WriteLiteral("</div>\r\n\r\n<p>\r\n");
            Write(
#nullable restore
#line (8,3)-(8,15) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/DesignTime.cshtml"
Foo(Bar.Baz)

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("\r\n");
            Write(
#nullable restore
#line (9,2)-(9,6) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/DesignTime.cshtml"
Foo(

#line default
#line hidden
#nullable disable
            item => new Template(async(__razor_template_writer) => {
                PushWriter(__razor_template_writer);
                WriteLiteral("<p>Bar ");
                Write(
#nullable restore
#line (9,15)-(9,18) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/DesignTime.cshtml"
baz

#line default
#line hidden
#nullable disable
                );
                WriteLiteral(" Biz</p>");
                PopWriter();
            }
            )
#nullable restore
#line (9,26)-(9,27) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/DesignTime.cshtml"
)

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("\r\n</p>\r\n\r\n");
            DefineSection("Footer", async() => {
                WriteLiteral("\r\n    <p>Foo</p>\r\n    ");
                Write(
#nullable restore
#line (14,6)-(14,9) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/DesignTime.cshtml"
bar

#line default
#line hidden
#nullable disable
                );
                WriteLiteral("\r\n");
            }
            );
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
