#pragma checksum "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Implements.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "668986313132d43ea69290e3a9fa026efcdd9b84e34b0fe6ef95f8096bd84385"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles.TestFiles_IntegrationTests_CodeGenerationIntegrationTest_Implements_Runtime), @"default", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Implements.cshtml")]
namespace Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA256", @"668986313132d43ea69290e3a9fa026efcdd9b84e34b0fe6ef95f8096bd84385", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Implements.cshtml")]
    public class TestFiles_IntegrationTests_CodeGenerationIntegrationTest_Implements_Runtime : IDisposable
    {
        #pragma warning disable 1998
        public async System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
        }
        #pragma warning restore 1998
#nullable restore
#line 3 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Implements.cshtml"
            
    void IDisposable.Dispose() { }

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
