#pragma checksum "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/InheritsAndImplements.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "1efd78a4e0070e4ee09b9f26bcaaf5132df6d5c771ee178bef8c9b981a4dd432"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles.TestFiles_IntegrationTests_CodeGenerationIntegrationTest_InheritsAndImplements_Runtime), @"default", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/InheritsAndImplements.cshtml")]
namespace Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA256", @"1efd78a4e0070e4ee09b9f26bcaaf5132df6d5c771ee178bef8c9b981a4dd432", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/InheritsAndImplements.cshtml")]
    public class TestFiles_IntegrationTests_CodeGenerationIntegrationTest_InheritsAndImplements_Runtime : 
#nullable restore
#line 1 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/InheritsAndImplements.cshtml"
foo.bar<baz<biz>>.boz

#line default
#line hidden
#nullable disable
    , IDisposable, IList
    {
        #pragma warning disable 1998
        public async System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
#nullable restore
#line (5,2)-(5,7) 6 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/InheritsAndImplements.cshtml"
Write(foo());

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
