#pragma checksum "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/NullConditionalExpressions.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "bb8d8c34e68ddf6c5aaf34e0f1c5f319f48c57e4ba3661228c4eeeb8bb9b79ce"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles.TestFiles_IntegrationTests_CodeGenerationIntegrationTest_NullConditionalExpressions_Runtime), @"default", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/NullConditionalExpressions.cshtml")]
namespace Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA256", @"bb8d8c34e68ddf6c5aaf34e0f1c5f319f48c57e4ba3661228c4eeeb8bb9b79ce", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/NullConditionalExpressions.cshtml")]
    public class TestFiles_IntegrationTests_CodeGenerationIntegrationTest_NullConditionalExpressions_Runtime
    {
        #pragma warning disable 1998
        public async System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line (2,5)-(2,18) 6 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/NullConditionalExpressions.cshtml"
Write(ViewBag?.Data);

#line default
#line hidden
#nullable disable
#nullable restore
#line (3,5)-(3,27) 6 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/NullConditionalExpressions.cshtml"
Write(ViewBag.IntIndexer?[0]);

#line default
#line hidden
#nullable disable
#nullable restore
#line (4,5)-(4,31) 6 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/NullConditionalExpressions.cshtml"
Write(ViewBag.StrIndexer?["key"]);

#line default
#line hidden
#nullable disable
#nullable restore
#line (5,5)-(5,46) 6 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/NullConditionalExpressions.cshtml"
Write(ViewBag?.Method(Value?[23]?.More)?["key"]);

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n");
#nullable restore
#line (8,1)-(8,14) 6 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/NullConditionalExpressions.cshtml"
Write(ViewBag?.Data);

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n");
#nullable restore
#line (9,1)-(9,23) 6 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/NullConditionalExpressions.cshtml"
Write(ViewBag.IntIndexer?[0]);

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n");
#nullable restore
#line (10,1)-(10,27) 6 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/NullConditionalExpressions.cshtml"
Write(ViewBag.StrIndexer?["key"]);

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n");
#nullable restore
#line (11,1)-(11,42) 6 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/NullConditionalExpressions.cshtml"
Write(ViewBag?.Method(Value?[23]?.More)?["key"]);

#line default
#line hidden
#nullable disable
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
