#pragma checksum "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/ParserError.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "2ea704d333b7a4d377b389409cc282c6500f60cbc098fd01acffeac4b61d150b"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles.TestFiles_IntegrationTests_CodeGenerationIntegrationTest_ParserError_Runtime), @"default", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/ParserError.cshtml")]
namespace Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha256", @"2ea704d333b7a4d377b389409cc282c6500f60cbc098fd01acffeac4b61d150b", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/ParserError.cshtml")]
    public class TestFiles_IntegrationTests_CodeGenerationIntegrationTest_ParserError_Runtime
    {
        #pragma warning disable 1998
        public async System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line (1,3)-(5,2) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/ParserError.cshtml"

/*
int i =10;
int j =20;
}

#line default
#line hidden
#nullable disable

        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
