#pragma checksum "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "f52e72ba69034334ab681d1f5e91cd50788cbfc0d1390104ee1e60d95d4ca443"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles.TestFiles_IntegrationTests_CodeGenerationIntegrationTest_Usings_Runtime), @"default", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml")]
namespace Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles
{
    #line default
#nullable restore
#line (1,2)-(2,1) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml"
using System.IO

#nullable disable
    ;
#nullable restore
#line (2,2)-(3,1) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml"
using Foo = System.Text.Encoding

#nullable disable
    ;
#nullable restore
#line (3,2)-(4,1) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml"
using System

#nullable disable
    ;
#nullable restore
#line (5,2)-(6,1) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml"
using static System

#nullable disable
    ;
#nullable restore
#line (6,2)-(7,1) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml"
using static System.Console

#nullable disable
    ;
#nullable restore
#line (7,2)-(8,1) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml"
using static global::System.Text.Encoding

#line default
#line hidden
#nullable disable
    ;
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha256", @"f52e72ba69034334ab681d1f5e91cd50788cbfc0d1390104ee1e60d95d4ca443", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml")]
    public class TestFiles_IntegrationTests_CodeGenerationIntegrationTest_Usings_Runtime
    {
        #pragma warning disable 1998
        public async System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
            WriteLiteral("\r\n");
#nullable restore
#line (9,3)-(12,1) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml"
 
    using var disposable = (IDisposable)ViewData["disposable"];
    using System.IDisposable otherDisposable = (IDisposable)ViewData["otherdisposable"];

#line default
#line hidden
#nullable disable

            WriteLiteral("\r\n<p>Path\'s full type name is ");
            Write(
#nullable restore
#line (14,30)-(14,51) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml"
typeof(Path).FullName

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("</p>\r\n<p>Foo\'s actual full type name is ");
            Write(
#nullable restore
#line (15,36)-(15,56) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Usings.cshtml"
typeof(Foo).FullName

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("</p>");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
