#pragma checksum "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Utf8StringLiterals.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "a9c623e1825f01e590d8552e7404c7f6b86bd1b64994ff62ff0ccaca1c87b175"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCoreGeneratedDocument.TestFiles_IntegrationTests_CodeGenerationIntegrationTest_Utf8StringLiterals), @"mvc.1.0.razor-page", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Utf8StringLiterals.cshtml")]
namespace AspNetCoreGeneratedDocument
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Mvc;
    using global::Microsoft.AspNetCore.Mvc.Rendering;
    using global::Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line (2,2)-(2,19) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Utf8StringLiterals.cshtml"
using System.Text

#nullable disable
    ;
    #line default
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha256", @"a9c623e1825f01e590d8552e7404c7f6b86bd1b64994ff62ff0ccaca1c87b175", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Utf8StringLiterals.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemMetadataAttribute("Identifier", "/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Utf8StringLiterals.cshtml")]
    [global::System.Runtime.CompilerServices.CreateNewOnMetadataUpdateAttribute]
    #nullable restore
    internal sealed class TestFiles_IntegrationTests_CodeGenerationIntegrationTest_Utf8StringLiterals : global::Microsoft.AspNetCore.Mvc.RazorPages.Page
    #nullable disable
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n<div class=\"text-center\">\r\n");
#nullable restore
#line (6,7)-(18,5) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Utf8StringLiterals.cshtml"

        // UTF-8 string literal with lowercase u8 suffix
        ReadOnlySpan<byte> span1 = "hello"u8;
        
        // UTF-8 string literal with uppercase U8 suffix
        ReadOnlySpan<byte> span2 = "world"U8;
        
        // Empty UTF-8 string
        ReadOnlySpan<byte> empty = ""u8;
        
        // UTF-8 string with escape sequences
        ReadOnlySpan<byte> escaped = "hello\nworld"u8;
    

#line default
#line hidden
#nullable disable

            WriteLiteral("\r\n");
            WriteLiteral("    <p>");
            Write(
#nullable restore
#line (21,9)-(21,42) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Utf8StringLiterals.cshtml"
Encoding.UTF8.GetString("test"u8)

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("</p>\r\n    \r\n");
#nullable restore
#line (24,7)-(26,5) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Utf8StringLiterals.cshtml"

        var bytes = "data"u8;
    

#line default
#line hidden
#nullable disable

            WriteLiteral("    \r\n");
#nullable restore
#line (29,7)-(31,5) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Utf8StringLiterals.cshtml"

        ReadOnlySpan<byte> verbatim = @"path\to\file"u8;
    

#line default
#line hidden
#nullable disable

            WriteLiteral("</div>\r\n\r\n");
            Write(
#nullable restore
#line (34,2)-(34,6) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Utf8StringLiterals.cshtml"
code

#line default
#line hidden
#nullable disable
            );
            WriteLiteral(" {\r\n    // UTF-8 string in ");
            Write(
#nullable restore
#line (35,25)-(35,29) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Utf8StringLiterals.cshtml"
code

#line default
#line hidden
#nullable disable
            );
            WriteLiteral(@" block
    private ReadOnlySpan<byte> GetUtf8Data()
    {
        return ""code block data""u8;
    }
    
    private void ProcessUtf8()
    {
        ReadOnlySpan<byte> data = ""processing""U8;
        var result = Encoding.UTF8.GetString(data);
    }
}

");
        }
        #pragma warning restore 1998
#nullable restore
#line (48,13)-(54,1) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Utf8StringLiterals.cshtml"

    // UTF-8 string in @functions block
    private ReadOnlySpan<byte> GetFunctionData()
    {
        return "function data"u8;
    }

#line default
#line hidden
#nullable disable

        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<IndexModel> Html { get; private set; } = default!;
        #nullable disable
        #nullable restore
public global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<IndexModel> ViewData => (global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<IndexModel>)PageContext?.ViewData!;
#nullable disable
        public 
#nullable restore
#line (3,8)-(3,18) "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Utf8StringLiterals.cshtml"
IndexModel

#line default
#line hidden
#nullable disable
         Model => ViewData.Model;
    }
}
#pragma warning restore 1591
