// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT license. See License.txt in the project root for license information.

using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Razor.Test.Common;
using Xunit.Abstractions;
using WorkspacesSR = Microsoft.CodeAnalysis.Razor.Workspaces.Resources.SR;

namespace Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CodeActions;

public class ExtractToCodeBehindTests(FuseTestContext context, ITestOutputHelper testOutputHelper) : CohostCodeActionsEndpointTestBase(context, testOutputHelper)
{
    [FuseFact]
    public async Task ExtractToCodeBehind()
    {
        // Roslyn uses the first .cs document in a project to work out the "file header", and in these tests that is the
        // generated document, so we need to include the auto-generated header in the expected output. In FUSE however,
        // there is a #pragma before the comment, so it isn't seen as having a file header.
        var fileHeader = ForceRuntimeCodeGeneration
                ? ""
                : $"// <auto-generated/>{Environment.NewLine}";

        await VerifyCodeActionAsync(
            input: """
                <div></div>

                @co[||]de
                {
                    private int x = 1;
                }
                """,
            expected: """
                <div></div>


                """,
            codeActionName: WorkspacesSR.ExtractTo_CodeBehind_Title,
            additionalExpectedFiles: [
                (FileUri("File1.razor.cs"), $$"""
                    {{fileHeader}}namespace SomeProject
                    {
                        public partial class File1
                        {
                            private int x = 1;
                        }
                    }
                    """)]);
    }
}
