// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line hidden
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.AddMarkupContent(0, "<div method=\"post\" @onsubmit=\"() => { }\" @formname=\"named-form-handler\"></div>\r\n");
            __builder.OpenElement(1, "div");
            __builder.AddAttribute(2, "method", "post");
            __builder.AddAttribute(3, "@onsubmit", "() => { }");
            __builder.AddAttribute(4, "@formname", 
#nullable restore
#line 2 "x:\dir\subdir\Test\TestComponent.cshtml"
                                                      "named-form-handler"

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
