// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line hidden
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line (1,3)-(3,1) "x:\dir\subdir\Test\TestComponent.cshtml"

  var myValue = "Expression value";

#line default
#line hidden
#nullable disable

            __builder.OpenElement(0, "div");
            __builder.AddContent(1, 
#nullable restore
#line (4,7)-(4,14) "x:\dir\subdir\Test\TestComponent.cshtml"
myValue

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
