// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<global::Test.
#nullable restore
#line (1,2)-(1,13) "x:\dir\subdir\Test\TestComponent.cshtml"
MyComponent

#line default
#line hidden
#nullable disable
            >(0);
            __builder.CloseComponent();
            __builder.AddMarkupContent(1, "\r\n");
            __builder.OpenComponent<global::
#nullable restore
#line (2,2)-(2,18) "x:\dir\subdir\Test\TestComponent.cshtml"
Test.MyComponent

#line default
#line hidden
#nullable disable
            >(2);
            __builder.CloseComponent();
            __builder.AddMarkupContent(3, "\r\n");
            __builder.OpenComponent<global::
#nullable restore
#line (3,2)-(3,20) "x:\dir\subdir\Test\TestComponent.cshtml"
Test2.MyComponent2

#line default
#line hidden
#nullable disable
            >(4);
            __builder.CloseComponent();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
