#pragma checksum "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3622bfea97cd74debca0bca7d916a74d2012c57d"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles.TestFiles_IntegrationTests_CodeGenerationIntegrationTest_Templates_InFunctionsBlockWithTagHelper_Runtime), @"default", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml")]
namespace Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"3622bfea97cd74debca0bca7d916a74d2012c57d", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml")]
    public class TestFiles_IntegrationTests_CodeGenerationIntegrationTest_Templates_InFunctionsBlockWithTagHelper_Runtime
    {
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::DivTagHelper __DivTagHelper;
        #pragma warning disable 1998
        public async System.Threading.Tasks.Task ExecuteAsync()
        {
#line 2 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
  
    var people = new Person[]
    {
        new Person() { Name = "Ryan", Age = 95, };
    };

#line default
#line hidden
            WriteLiteral("\r\n");
#line 9 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
   await AnnounceBirthday(people[0]); 

#line default
#line hidden
            WriteLiteral("\r\n");
        }
        #pragma warning restore 1998
#line 11 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
            
    Task AnnounceBirthday(Person person)
    {
        var formatted = $"Mr. {person.Name}";
        

#line default
#line hidden
        __tagHelperExecutionContext = __tagHelperScopeManager.Begin("div", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "test", async() => {
            WriteLiteral("\r\n            <h3>Happy birthday ");
#line 16 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
                           Write(formatted);

#line default
#line hidden
            WriteLiteral("!</h3>\r\n        ");
        }
        );
        __DivTagHelper = CreateTagHelper<global::DivTagHelper>();
        __tagHelperExecutionContext.Add(__DivTagHelper);
        await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
        if (!__tagHelperExecutionContext.Output.IsContentModified)
        {
            await __tagHelperExecutionContext.SetOutputContentAsync();
        }
        Write(__tagHelperExecutionContext.Output);
        __tagHelperExecutionContext = __tagHelperScopeManager.End();
        WriteLiteral("\r\n");
        WriteLiteral("<ul>\r\n");
#line 20 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
         for (var i = 0; i < Age / 10; i++)
        {

#line default
#line hidden
        WriteLiteral("            <p>");
#line 22 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
           Write(i);

#line default
#line hidden
        WriteLiteral(" Happy birthday!</p>\r\n");
#line 23 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
        }

#line default
#line hidden
        WriteLiteral("        </ul>\r\n");
#line 25 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"

        if (person.Age < 20)
        {
            return;
        }

        

#line default
#line hidden
        WriteLiteral("<h4>Secret message</h4>\r\n");
#line 32 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
    }


    class Person
    {
        string Name { get; set; }
        int Age { get; set; }
    }

#line default
#line hidden
    }
}
#pragma warning restore 1591
