#pragma checksum "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlock.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "a51883ca89a403ee2b313e27b00ec9c13722672d"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles.TestFiles_IntegrationTests_CodeGenerationIntegrationTest_Templates_InFunctionsBlock_Runtime), @"default", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlock.cshtml")]
namespace Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"a51883ca89a403ee2b313e27b00ec9c13722672d", @"/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlock.cshtml")]
    public class TestFiles_IntegrationTests_CodeGenerationIntegrationTest_Templates_InFunctionsBlock_Runtime
    {
        #pragma warning disable 1998
        public async System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
#line 2 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlock.cshtml"
  
    var people = new Person[]
    {
        new Person() { Name = "Ryan", Age = 95, };
    };

#line default
#line hidden
            WriteLiteral("\r\n");
#line 9 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlock.cshtml"
   AnnounceBirthday(people[0]); 

#line default
#line hidden
            WriteLiteral("\r\n");
        }
        #pragma warning restore 1998
#line 11 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlock.cshtml"
            
    void AnnounceBirthday(Person person)
    {
        var formatted = $"Mr. {person.Name}";
        

#line default
#line hidden
        WriteLiteral("<div>\r\n            <h3>Happy birthday ");
#line 16 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlock.cshtml"
                           Write(formatted);

#line default
#line hidden
        WriteLiteral("!</h3>\r\n        </div>\r\n");
        WriteLiteral("<ul>\r\n");
#line 20 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlock.cshtml"
         for (var i = 0; i < Age / 10; i++)
        {

#line default
#line hidden
        WriteLiteral("            <p>");
#line 22 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlock.cshtml"
           Write(i);

#line default
#line hidden
        WriteLiteral(" Happy birthday!</p>\r\n");
#line 23 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlock.cshtml"
        }

#line default
#line hidden
        WriteLiteral("        </ul>\r\n");
#line 25 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlock.cshtml"

        if (person.Age < 20)
        {
            return;
        }

        

#line default
#line hidden
        WriteLiteral("<h4>Secret message</h4>\r\n");
#line 32 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlock.cshtml"
    }

    class Person
    {
        string Name { get; set; }
        int Age { get; set; }
    }

#line default
#line hidden
    }
}
#pragma warning restore 1591
