// <auto-generated/>
#pragma warning disable 1591
namespace Microsoft.AspNetCore.Razor.Language.IntegrationTests.TestFiles
{
    #line hidden
    public class TestFiles_IntegrationTests_CodeGenerationIntegrationTest_Templates_InFunctionsBlockWithTagHelper_DesignTime
    {
        private global::DivTagHelper __DivTagHelper;
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        ((System.Action)(() => {
#line 1 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
global::System.Object __typeHelper = "*, TestAssembly";

#line default
#line hidden
        }
        ))();
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static System.Object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        public async System.Threading.Tasks.Task ExecuteAsync()
        {
#line 2 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
  
    var people = new Person[]
    {
        new Person() { Name = "Ryan", Age = 95, };
    };

#line default
#line hidden
#line 9 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
   await AnnounceBirthday(people[0]); 

#line default
#line hidden
        }
        #pragma warning restore 1998
#line 11 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
            
    Task AnnounceBirthday(Person person)
    {
        var formatted = $"Mr. {person.Name}";
        

#line default
#line hidden
#line 16 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
                           __o = formatted;

#line default
#line hidden
        __DivTagHelper = CreateTagHelper<global::DivTagHelper>();
#line 17 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
              

        

#line default
#line hidden
#line 20 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
         for (var i = 0; i < Age / 10; i++)
        {
            

#line default
#line hidden
#line 22 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
           __o = i;

#line default
#line hidden
#line 22 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
                                       
        }

#line default
#line hidden
#line 24 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
             

        if (person.Age < 20)
        {
            return;
        }

        

#line default
#line hidden
#line 31 "TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Templates_InFunctionsBlockWithTagHelper.cshtml"
                                
    }


    class Person
    {
        string Name { get; set; }
        int Age { get; set; }
    }

#line default
#line hidden
    }
}
#pragma warning restore 1591
