#pragma checksum "Pages/Counter.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0de17e526cd536d59072aa0e924e99111b16b97a"
// <auto-generated/>
#pragma warning disable 1591
namespace MyApp.Pages
{
    #line hidden
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    public partial class Counter : global::Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.AddMarkupContent(0, "<h1>Counter</h1>");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
