name: Update TextMate Grammar files
on:
  schedule:
    - cron:  '0 2 * * 0'
  workflow_dispatch:
jobs:
  Create-Merge-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Check out branch
        run: |
          git checkout -b update-textmate
      - name: Run UpdateTextMate.ps1
        run: '& $env:GITHUB_ACTION_PATH/eng/scripts/UpdateTextMate.ps1'
        shell: pwsh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Update TextMate grammar files
          branch: update-textmate