#pragma checksum "Pages/Counter.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "fb93b97dc0d4885250500697f41ffde70decc444"
// <auto-generated/>
#pragma warning disable 1591
namespace MyApp.Pages
{
    #line hidden
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    public partial class Counter : global::Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.AddMarkupContent(0, "<h2>Counter</h2>\r\n");
            __builder.OpenElement(1, "h3");
            __builder.AddContent(2, "Current count: ");
#nullable restore
#line (3,21)-(3,26) 24 "Pages/Counter.razor"
__builder.AddContent(3, count);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.AddMarkupContent(4, "\r\n");
            __builder.AddMarkupContent(5, "<button @onclick=\"Click\">Click me</button>");
        }
        #pragma warning restore 1998
#nullable restore
#line 7 "Pages/Counter.razor"
 
    private int count;

    public void Click() => count++;

    [Parameter] public int IncrementAmount { get; set; }

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
